"""Première migration

Revision ID: 448e7ad9d6f8
Revises: 
Create Date: 2022-03-18 11:19:11.970956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '448e7ad9d6f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=150), nullable=True),
    sa.Column('slug', sa.String(length=150), nullable=True),
    sa.Column('contenu', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    # ### end Alembic commands ###
