"""Ajout de la date à Article

Revision ID: c0cc3f2d1b20
Revises: 448e7ad9d6f8
Create Date: 2022-03-18 11:27:26.814299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0cc3f2d1b20'
down_revision = '448e7ad9d6f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'date')
    # ### end Alembic commands ###
